//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Becky.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Becky.Data.DataAccess;
    using System.Data.Entity.Core.Objects;
    
    public partial class BeckyContext : DbContext, IDbContext
    {
        public BeckyContext()
            : base("name=BeckyContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<LookupPhotoType> LookupPhotoTypes { get; set; }
        public virtual DbSet<LookupRestaurantType> LookupRestaurantTypes { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<RestaurantBranch> RestaurantBranches { get; set; }
        public virtual DbSet<RestaurantPhoto> RestaurantPhotoes { get; set; }
        public virtual DbSet<RestaurantRating> RestaurantRatings { get; set; }
        public virtual DbSet<RestaurantReview> RestaurantReviews { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<ViewRestaurant> ViewRestaurants { get; set; }
        public virtual DbSet<ViewReview> ViewReviews { get; set; }
        public ObjectContext ObjectContext
        {
            get { return this.GetObjectContext(); }
        }
    
        public new IDbSet<TEntity> Set<TEntity>() where TEntity : class
        {
            return base.Set<TEntity>();
        }
    
        public new int SaveChanges()
        {
            return base.SaveChanges();
        }
        }
}
