//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Becky.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRestaurant
    {
        public string Name { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
        public bool IsActive { get; set; }
        public string PhotoSource { get; set; }
        public string Type { get; set; }
        public int Id { get; set; }
    }
}
