//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Becky.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewReview
    {
        public int Id { get; set; }
        public string ReviewText { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ProfilePictureUrl { get; set; }
        public string ReviewTitle { get; set; }
        public int RestaurantBranchId { get; set; }
    }
}
